name: 'elt_transform'

config-version: 2
version: '1.0'

profile: 'elt-transform'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  elt_transform:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

clean-targets:
  - "target"